n = input('Digite Algo:')
print(type(n))
print('Alpha numérico: ', n.isalnum())
print('Número: ', n.isnumeric())
print('Decimal: ', n.isdecimal())
print('Letras: ', n.isalpha())
print('Letra Maiuscula: ', n.isupper())
print('Letra Minuscula:',  n.islower())
